name: Auto Reset JustRunMyApp Timer

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  reset-timer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Auto Reset Script
      env:
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        MY_COOKIE: ${{ secrets.MY_COOKIE }}
      run: node autoreset.js

    - name: Upload Screenshot Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: page-screenshot
        path: page_preview.png
